/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthOauthRouteImport } from './routes/auth/oauth'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account/index'
import { Route as ProtectedAccountSettingsRouteImport } from './routes/_protected/account/settings'
import { Route as ProtectedAccountSearchRouteImport } from './routes/_protected/account/search'
import { Route as ProtectedAccountDocumentsRouteImport } from './routes/_protected/account/documents'
import { Route as ProtectedAccountChatRouteImport } from './routes/_protected/account/chat'

const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountSettingsRoute =
  ProtectedAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAccountSearchRoute = ProtectedAccountSearchRouteImport.update({
  id: '/account/search',
  path: '/account/search',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountDocumentsRoute =
  ProtectedAccountDocumentsRouteImport.update({
    id: '/account/documents',
    path: '/account/documents',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAccountChatRoute = ProtectedAccountChatRouteImport.update({
  id: '/account/chat',
  path: '/account/chat',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/profile': typeof ProtectedProfileRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/auth/': typeof AuthIndexRoute
  '/account/chat': typeof ProtectedAccountChatRoute
  '/account/documents': typeof ProtectedAccountDocumentsRoute
  '/account/search': typeof ProtectedAccountSearchRoute
  '/account/settings': typeof ProtectedAccountSettingsRoute
  '/account': typeof ProtectedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/profile': typeof ProtectedProfileRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/auth': typeof AuthIndexRoute
  '/account/chat': typeof ProtectedAccountChatRoute
  '/account/documents': typeof ProtectedAccountDocumentsRoute
  '/account/search': typeof ProtectedAccountSearchRoute
  '/account/settings': typeof ProtectedAccountSettingsRoute
  '/account': typeof ProtectedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/account/chat': typeof ProtectedAccountChatRoute
  '/_protected/account/documents': typeof ProtectedAccountDocumentsRoute
  '/_protected/account/search': typeof ProtectedAccountSearchRoute
  '/_protected/account/settings': typeof ProtectedAccountSettingsRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deferred'
    | '/profile'
    | '/auth/error'
    | '/auth/oauth'
    | '/auth/'
    | '/account/chat'
    | '/account/documents'
    | '/account/search'
    | '/account/settings'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/profile'
    | '/auth/error'
    | '/auth/oauth'
    | '/auth'
    | '/account/chat'
    | '/account/documents'
    | '/account/search'
    | '/account/settings'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/deferred'
    | '/_protected/profile'
    | '/auth/error'
    | '/auth/oauth'
    | '/auth/'
    | '/_protected/account/chat'
    | '/_protected/account/documents'
    | '/_protected/account/search'
    | '/_protected/account/settings'
    | '/_protected/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeferredRoute: typeof DeferredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account/settings': {
      id: '/_protected/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof ProtectedAccountSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account/search': {
      id: '/_protected/account/search'
      path: '/account/search'
      fullPath: '/account/search'
      preLoaderRoute: typeof ProtectedAccountSearchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account/documents': {
      id: '/_protected/account/documents'
      path: '/account/documents'
      fullPath: '/account/documents'
      preLoaderRoute: typeof ProtectedAccountDocumentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account/chat': {
      id: '/_protected/account/chat'
      path: '/account/chat'
      fullPath: '/account/chat'
      preLoaderRoute: typeof ProtectedAccountChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedAccountChatRoute: typeof ProtectedAccountChatRoute
  ProtectedAccountDocumentsRoute: typeof ProtectedAccountDocumentsRoute
  ProtectedAccountSearchRoute: typeof ProtectedAccountSearchRoute
  ProtectedAccountSettingsRoute: typeof ProtectedAccountSettingsRoute
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedAccountChatRoute: ProtectedAccountChatRoute,
  ProtectedAccountDocumentsRoute: ProtectedAccountDocumentsRoute,
  ProtectedAccountSearchRoute: ProtectedAccountSearchRoute,
  ProtectedAccountSettingsRoute: ProtectedAccountSettingsRoute,
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthOauthRoute: typeof AuthOauthRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthOauthRoute: AuthOauthRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeferredRoute: DeferredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
