/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutAccountIndexRouteImport } from './routes/_pathlessLayout/account/index'
import { Route as PathlessLayoutAccountSettingsRouteImport } from './routes/_pathlessLayout/account/settings'
import { Route as PathlessLayoutAccountSearchRouteImport } from './routes/_pathlessLayout/account/search'
import { Route as PathlessLayoutAccountDocumentsRouteImport } from './routes/_pathlessLayout/account/documents'
import { Route as PathlessLayoutAccountChatRouteImport } from './routes/_pathlessLayout/account/chat'

const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutAccountIndexRoute =
  PathlessLayoutAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutAccountSettingsRoute =
  PathlessLayoutAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutAccountSearchRoute =
  PathlessLayoutAccountSearchRouteImport.update({
    id: '/account/search',
    path: '/account/search',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutAccountDocumentsRoute =
  PathlessLayoutAccountDocumentsRouteImport.update({
    id: '/account/documents',
    path: '/account/documents',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutAccountChatRoute =
  PathlessLayoutAccountChatRouteImport.update({
    id: '/account/chat',
    path: '/account/chat',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deferred': typeof DeferredRoute
  '/account/chat': typeof PathlessLayoutAccountChatRoute
  '/account/documents': typeof PathlessLayoutAccountDocumentsRoute
  '/account/search': typeof PathlessLayoutAccountSearchRoute
  '/account/settings': typeof PathlessLayoutAccountSettingsRoute
  '/account': typeof PathlessLayoutAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deferred': typeof DeferredRoute
  '/account/chat': typeof PathlessLayoutAccountChatRoute
  '/account/documents': typeof PathlessLayoutAccountDocumentsRoute
  '/account/search': typeof PathlessLayoutAccountSearchRoute
  '/account/settings': typeof PathlessLayoutAccountSettingsRoute
  '/account': typeof PathlessLayoutAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/deferred': typeof DeferredRoute
  '/_pathlessLayout/account/chat': typeof PathlessLayoutAccountChatRoute
  '/_pathlessLayout/account/documents': typeof PathlessLayoutAccountDocumentsRoute
  '/_pathlessLayout/account/search': typeof PathlessLayoutAccountSearchRoute
  '/_pathlessLayout/account/settings': typeof PathlessLayoutAccountSettingsRoute
  '/_pathlessLayout/account/': typeof PathlessLayoutAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deferred'
    | '/account/chat'
    | '/account/documents'
    | '/account/search'
    | '/account/settings'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deferred'
    | '/account/chat'
    | '/account/documents'
    | '/account/search'
    | '/account/settings'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/auth'
    | '/deferred'
    | '/_pathlessLayout/account/chat'
    | '/_pathlessLayout/account/documents'
    | '/_pathlessLayout/account/search'
    | '/_pathlessLayout/account/settings'
    | '/_pathlessLayout/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeferredRoute: typeof DeferredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/account/': {
      id: '/_pathlessLayout/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PathlessLayoutAccountIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/account/settings': {
      id: '/_pathlessLayout/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof PathlessLayoutAccountSettingsRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/account/search': {
      id: '/_pathlessLayout/account/search'
      path: '/account/search'
      fullPath: '/account/search'
      preLoaderRoute: typeof PathlessLayoutAccountSearchRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/account/documents': {
      id: '/_pathlessLayout/account/documents'
      path: '/account/documents'
      fullPath: '/account/documents'
      preLoaderRoute: typeof PathlessLayoutAccountDocumentsRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/account/chat': {
      id: '/_pathlessLayout/account/chat'
      path: '/account/chat'
      fullPath: '/account/chat'
      preLoaderRoute: typeof PathlessLayoutAccountChatRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutAccountChatRoute: typeof PathlessLayoutAccountChatRoute
  PathlessLayoutAccountDocumentsRoute: typeof PathlessLayoutAccountDocumentsRoute
  PathlessLayoutAccountSearchRoute: typeof PathlessLayoutAccountSearchRoute
  PathlessLayoutAccountSettingsRoute: typeof PathlessLayoutAccountSettingsRoute
  PathlessLayoutAccountIndexRoute: typeof PathlessLayoutAccountIndexRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutAccountChatRoute: PathlessLayoutAccountChatRoute,
  PathlessLayoutAccountDocumentsRoute: PathlessLayoutAccountDocumentsRoute,
  PathlessLayoutAccountSearchRoute: PathlessLayoutAccountSearchRoute,
  PathlessLayoutAccountSettingsRoute: PathlessLayoutAccountSettingsRoute,
  PathlessLayoutAccountIndexRoute: PathlessLayoutAccountIndexRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  DeferredRoute: DeferredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
